-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 이때 결과는 보호 시작일이 빠른 순으로 조회해야합니다. 

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME FROM ANIMAL_INS INNER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID WHERE ANIMAL_OUTS.DATETIME<ANIMAL_INS.DATETIME ORDER BY ANIMAL_INS.DATETIME;

-- SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS I, ANIMAL_OUTS O WHERE I.DATETIME > O.DATETIME AND I.ANIMAL_ID = O.ANIMAL_ID ORDER BY I.DATETIME;