-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 이때 결과는 보호 기간이 긴 순으로 조회해야 합니다.

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME FROM ANIMAL_OUTS INNER JOIN ANIMAL_INS ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID ORDER BY ANIMAL_OUTS.DATETIME-ANIMAL_INS.DATETIME DESC LIMIT 2;